### ISSUE TITLE
not clear on how to release?

### ISSUE THREAD

**Issue by spences10** [webpro/release-it#204]
Hi @webpro, thanks for this repo 👍 

I've started using it for some of my projects and thought I had it figured out but the last couple of times I have had my CI not create a release.

I presumed that release it bumped up the version number each time but now I'm not sure.

From looking at your projects that use `release-it.` I can't glean what to put into the comment message to do a release.

![image](https://user-images.githubusercontent.com/234708/35027844-ddebc4ec-fb4a-11e7-9dba-5681f4b3439a.png)

I'm running a Gatsby blog with `release-it` in the Travis CI, here is my `.release-it.json`:

```json
{
  "src": {
    "tagName": "v%s",
    "push": false
  },
  "github": {
    "release": true
  },
  "npm":{
    "publish": false
  }
}
```

and the `.travis.yml`:

```yml
sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '9'

before_script:
  - npm prune

script:
  - npm i -g now@canary
  - npm run clean
  - npm run build
  - npm run deploy

after_script: 
  - if [ "$TRAVIS_BRANCH" = "development" ]; then npm run alias:dev; fi 
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run alias:prod; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then npm run release; fi
  - npm run cleanup

env:
global:
    secure: removed
```
